#!/usr/bin/env python3
"""Derive <tree>/configs/t2-rk3568-installer_defconfig from the plain defconfig.

Only CONFIG_BOOTCOMMAND differs: the *installer* image is the one the card
carries in its loader partition and boots the card's installer tree (mmc1,
whose extlinux `default` is the t2-installer entry with t2.mode=flash), falling
back to the eMMC if that scan boots nothing.  The eMMC always carries the
*plain* image, so the installer bootcmd must never land on p1.

This used to be a hand-made copy, which silently went stale: the preboot/gate
work was added to the plain defconfig and the installer image kept building
with the old preboot.  Deriving it on every build makes that impossible.

Usage: gen-installer-defconfig.py [UBOOT_TREE]
UBOOT_TREE defaults to <repo>/build/uboot; u-boot/build.sh passes its tree.
"""

import pathlib
import sys

HERE = pathlib.Path(__file__).resolve().parent
ROOT = HERE.parent
DEFAULT_TREE = ROOT / "build" / "uboot"

INSTALLER_BOOTCMD = (
    '"if test x${t2_leds} = x1; then led power-led-red on; led power-led-green off; fi; '
    "echo T2: installer: booting the SD card; bootflow scan -lb mmc1; "
    'if fatload mmc 0:3 ${loadaddr} /extlinux/extlinux.conf; then bootflow scan -lb mmc0; fi"'
)

HEADER = """# GENERATED by gen-installer-defconfig.py from t2-rk3568_defconfig - do not
# edit.  Only CONFIG_BOOTCOMMAND differs: this is the *installer* image (the
# card's loader partition); the eMMC carries the plain image.
"""


def main(argv: list[str]) -> int:
    tree = pathlib.Path(argv[1]).resolve() if len(argv) > 1 else DEFAULT_TREE
    configs = tree / "configs"
    plain = configs / "t2-rk3568_defconfig"
    dst = configs / "t2-rk3568-installer_defconfig"

    if not plain.is_file():
        print(f"{plain}: missing - install the plain defconfig first", file=sys.stderr)
        return 1

    text = plain.read_text()
    bootcmd = [l for l in text.splitlines() if l.startswith("CONFIG_BOOTCOMMAND=")]
    if not bootcmd:
        print(f"{plain}: no CONFIG_BOOTCOMMAND", file=sys.stderr)
        return 1
    dst.write_text(HEADER + text.replace(bootcmd[0], "CONFIG_BOOTCOMMAND=" + INSTALLER_BOOTCMD, 1))
    print(f"wrote {dst}")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
